.circleci/config.yml, deploy/Makefile, deploy/docker/Dockerfile, deploy/env/dev/values.yaml, deploy/env/prod/values.yaml, deploy/values.yaml
Instead of the original plan where the deployment was controlled by a different repository, move the deployment functionality here (we will completely remove the other repository after we confirm all works here)
=> Use same repository for app deployment

src/layout/_page-section.scss
This is just to update the styleguide to reflect the changes in: https://github.com/greenpeace/planet4-plugin-blocks/pull/618
=> PLANET-3841: Columns block: font (and size) changing when adding paragraph in block descriptions 

src/layout/_forms.scss
This is a companion PR for: 
https://github.com/greenpeace/planet4-master-theme/pull/868
Looks like a lot of changes, in reality, I just added the `body:not(.wp-admin) { ... }` wrapper.
=> PLANET-3903: Fix rendering of blocks in the editor

src/layout/_cookies.scss
This flex property was probably introduced by mistake when removing a few lines from the previous commit (which also had color changes).
Causes this:
=> Remove display flex property

src/layout/_page-header.scss
After greenpeace/planet4-master-theme@022b634dcaa7e1797d53cd513b369a502a4f4d6c page header markup is visible even when there is no header content. So this eliminates its padding. 
I added the `!important` since we have some more explicit campaign overrides.
=> PLANET-4241 - Eliminate Header padding when there is no content

src/base/_colors.scss, src/components/_buttons.scss
Ref: https://jira.greenpeace.org/browse/PLANET-4208
Define some extra css classes to be used by Gutenberg
=> PLANET-4208 - Add palette classes

src/campaigns/themes/_theme_antarctic.scss, src/campaigns/themes/_theme_arctic.scss, src/campaigns/themes/_theme_climate.scss, src/campaigns/themes/_theme_forest.scss, src/campaigns/themes/_theme_oceans.scss, src/campaigns/themes/_theme_oil.scss, src/campaigns/themes/_theme_plastic.scss
Ref: https://jira.greenpeace.org/browse/PLANET-4357
This is a mirror of greenpeace/planet4-plugin-blocks#665 so the changes are there after the Gutenberg switch.
=> PLANET-4357 Enable skewed header background for the plastic campaign

src/layout/_footer.scss
This addresses bullet point 3 in the ticket: 
- Footer - CC icon not aligned vertically with Greenpeace International 2019 text
Ref: https://jira.greenpeace.org/browse/PLANET-4589
=> CPP - Minor frontend issues introduced

src/layout/_tables.scss
* only set the background color of rows if no color was specified in the
block settings (in which case it will have `has-background` class.
=> PLANET-4674 Make table block respect color settings.

src/layout/_cookies.scss
Ref: https://jira.greenpeace.org/browse/PLANET-4740
Master Theme PR: https://github.com/greenpeace/planet4-master-theme/pull/1009 
Blocks Plugin PR: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/215
Note: this also fixes a background issue in mobile:
=> PLANET-4740: CSS: Remove :not(#hidecookie) rule

src/components/_skip-links.scss
Added !important to the margin and padding of the _skip-links ul so that it won't push the overlay down
Ref: https://jira.greenpeace.org/browse/PLANET-4927
=> PLANET-4927 Planet 4 Bug Report: Page, Evergreen: Spacing issue when using background image

src/layout/_breadcrumbs.scss
After the HTML tag change, the link lost its color due to a specificity conflict with the `_reboot` stylesheet.
Ref: https://jira.greenpeace.org/browse/PLANET-4937
=> PLANET-4937: Search results post type should use an a tag instead of a button that behaves like an a tag

src/layout/_footer.scss, src/layout/_navbar.scss
Hold on: this passed UAT but I've found a conflict with another ticket (PLANET-5001).
Will remove the `!important` rules and rearrange the CSS precedence if needed.
Ref: https://jira.greenpeace.org/browse/PLANET-5000
=> PLANET-5000: Rollover color of primary navigation (footer and header) links is wrong

src/layout/_tables.scss
Reverts greenpeace/planet4-styleguide#51
Making the selector more specific with `:not()` could cause issues in downstream css, we'll include another fix in https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/270
=> Revert "PLANET-5037 Remove table background colors in spreadsheets"

src/layout/_navbar.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5063
This helps to differentiate buttons (eg. Donate) that don't have
a `.nav-link` class and follow another color palette.
Also removed the duplicate color for `.btn-donate`. We already have that
on the buttons component.
=> PLANET-5063 Make navbar text link colors more explicit

src/base/_body.scss, src/layout/_page-header.scss
This PR is for two tickets:
- https://jira.greenpeace.org/browse/PLANET-5033
- https://jira.greenpeace.org/browse/PLANET-4965
It also includes adding link styles to `_body.scss`, following the removal of the `base` folder in the master-theme repository (see https://github.com/greenpeace/planet4-master-theme/pull/1086).
=> Planet 5033 - White background

src/base/_colors.scss, src/layout/_tables.scss
See https://jira.greenpeace.org/browse/PLANET-5058
We want to offer the same color options for the Table block as we do for the Spreadsheet block. The only difference is that tables also have a footer, which requires an additional color. This PR takes care of 3 things:
- Create the color variables used for both tables and spreadsheets
- Remove background colors set in the `_tables.scss` file as they are now defined in override file in the planet4-plugin-gutenberg-blocks repo (see [this PR]( https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/278))
- Update header font size in bigger screens
See corresponding master-theme PR [here](https://github.com/greenpeace/planet4-master-theme/pull/1093)
=> Planet 5058 - Table background colors

src/base/_body.scss, src/components/_buttons.scss, src/layout/_footer.scss, src/layout/_navbar.scss
This is a non-exhaustive list of added variables that child-themes could use for easier customisation of Planet4 (see [PLANET-5114](https://jira.greenpeace.org/browse/PLANET-5114) for more details). The ones listed below are already in the code and could be used right away, but maybe they need to be renamed?
- Navigation bar background color: [--campaign_nav_color](https://github.com/greenpeace/planet4-styleguide/blob/master/src/layout/_navbar.scss#L83)
- Footer background color: [--footer_color](https://github.com/greenpeace/planet4-styleguide/blob/master/src/layout/_footer.scss#L47)
- Footer links color: [--footer_links_color](https://github.com/greenpeace/planet4-styleguide/blob/master/src/layout/_footer.scss#L68)
- Spreadsheet header background color: …
=> PLANET-5114 Add css variables for easier child-theme customisation

src/base/_colors.scss
Removing unused colors from the palette.
Ref: https://jira.greenpeace.org/browse/PLANET-5036
Test instance: https://k8s.p4.greenpeace.org/test-deimos/chi-siamo/
Related PRs:
https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/301
https://github.com/greenpeace/planet4-master-theme/pull/1112
https://github.com/greenpeace/planet4-plugin-gutenberg-engagingnetworks/pull/51
=> PLANET-5036: Reset the colors palette for P4

.circleci/config.yml
This adds two extra jobs when we have a new commit merged into master. Both jobs are currently require a manual approval.
1. It creates a new tag
2. Bump styleguide to this latest tag in the 3 repos that use the submodule
This depends on the script added at greenpeace/planet4-circleci#32
=> Add CI job to auto-promote to tag

src/base/_typography.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5294
> the numbered lists ("ol" tag) should follow the same typography rules as bullet lists ("ul" tag)
I took off the `ul` selector so that `li` tags would follow these rules, be it in `ol`, `ul` or `menu`.
A page with lists is available on test env https://k8s.p4.greenpeace.org/test-phobos/list-test/ .  
Locally, create a page and add bullet list and ordered list, they should have the same font-size and line-height, in the backend and on the frontend.
=> PLANET-5294: Apply list typography to ordered lists

.circleci/config.yml, .gitignore, .pa11y, README.md, deploy/Makefile, gulpfile.js, package-lock.json, package.json
Ref: https://jira.greenpeace.org/browse/PLANET-5510
Ref: https://jira.greenpeace.org/browse/PLANET-5275
Runs accessibility tests on the style guide.
- on a feature branch, the CI fails the `test-a11y` job if errors are found
- on deploy, it should just produce a report
Report is available [in html in CI artifacts](https://414-189984681-gh.circle-artifacts.com/0/%7E/app/deploy/docker/source/pa11y/index.html)
Command `gulp test` will run the accessibility test (local webserver has to be running).  
`npm` will install pa11y dependencies in development.
=> PLANET-5510: Run accessibility tests on style guide

src/base/_fonts.scss
https://jira.greenpeace.org/browse/PLANET-5563
* We need to add a preload tag in the head anyway, so it seems better to
keep both together.
=> PLANET-5563 Remove from css so we can load in head

src/layout/_page-header.scss
See https://jira.greenpeace.org/browse/PLANET-5465
- Broken version: https://k8s.p4.greenpeace.org/test-iocaste/act/join-the-movement-for-clean-air/
- Fixed version: https://k8s.p4.greenpeace.org/test-mars/act/join-the-movement-for-clean-air/
=> PLANET-5465 Remove empty space at top of page when no header

src/layout/_page-header.scss
See https://jira.greenpeace.org/browse/PLANET-5465
A fix was previously pushed for this issue using `!important` for the new margin value, but this caused issues in campaign pages so we need to remove it. The fix still works in "normal" pages though 🙂 
- Broken version: https://k8s.p4.greenpeace.org/test-iocaste/act/join-the-movement-for-clean-air/
- Fixed version: https://k8s.p4.greenpeace.org/test-mars/act/join-the-movement-for-clean-air/
=> PLANET-5465 Remove important to fix campaign pages

src/base/_colors.scss, src/components/_buttons.scss, src/layout/_cookies.scss, src/layout/_navbar.scss
See https://jira.greenpeace.org/browse/PLANET-5501
- Apply 4px radius to all button styles
- Use Roboto and font-weight bold
- Use `text-transform: capitalize`
- Add a `text-transform-none` class
- Primary button background color is changing to #F36B35
- Cookies button should follow secondary button styles
- Remove `btn-medium` class as it just duplicates the "regular" button styles
- Remove some of the RTL-related overrides
- [master-theme](https://github.com/greenpeace/planet4-master-theme/pull/1205)
- [gutenberg-blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/413)
=> PLANET-5501 - Consistent styles for buttons

src/components/_buttons.scss
See https://jira.greenpeace.org/browse/PLANET-5644
We need to enforce `text-transform: none;` for the donate button, since otherwise it takes the `text-transform: uppercase` applied to the `.top-navigation` class ([here](https://github.com/greenpeace/planet4-styleguide/blob/master/src/layout/_navbar.scss#L78))
See the fixed version here: https://www-dev.greenpeace.org/test-jupiter/
- master-theme: https://github.com/greenpeace/planet4-master-theme/pull/1224
- gutenberg-blocks: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/426
=> PLANET-5644 Remove text transform on buttons

src/base/_typography.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5368
> At the moment H3 (1.375rem) is smaller than H4 (1.5rem) on mobile. 
Review of heading size based on ticket recommendations.
- On mobile size: h4 and h5 are downsized
- On regular screen size: h4 is downsized
| | Before fix | After fix |
| --- | --- | --- |
| mobile | ![Screenshot from 2020-11-25 19-22-04](https://user-images.githubusercontent.com/617346/100269494-ed4ef600-2f56-11eb-91ee-e014ae5cd4d7.png) | ![Screenshot from 2020-11-25 19-30-48](https://user-images.githubusercontent.com/617346/100269523-f6d85e00-2f56-11eb-9fc5-ff1a0bec0a8f.png) |
| regular | ![Screenshot from 2020-11-25 19-36-21](https://user-images.githubusercontent.com/617346/100269597-17081d00-2f57-11eb-9fd9-47a5d1b3a219.png) | ![Screenshot from 2020-11-25 …
=> PLANET-5368: Fix H3/H4 font sizes on mobile

src/base/_colors.scss, src/components/_buttons.scss, src/components/_spinner.scss, src/layout/_navbar.scss
See https://jira.greenpeace.org/browse/PLANET-5842
- ~~#63bbfd = $blue-60~~
- ~~($grey-60) = $shadow-color~~
- ~~#f6f4e7 = $single-bg~~
- ~~#aed4c7 = $active~~
- ~~#b0d4c8 = $body-bg~~
- ~~#a7e021 = $inch-worm~~
- ~~#e51538 = $crimson~~
- ~~#5c1f10 = $brown-header~~
- ~~#003300 = $green~~
- ~~#264042 = $darkb-blue-text~~
- ~~#004d53 = $heading~~
- ~~#115247 = $search-text-color~~
- ~~#186a70 = $genoa~~
- ~~#017e7a = $percentage-text~~
- #418482 = $faded-jade => actually used in search page for search bar border, will be replaced in https://jira.greenpeace.org/browse/PLANET-5843
- ~~#22938d = $blue-elm~~
- ~~#67b2af = $light-blue~~
- ~~#1bb6d6 = $java~~
- ~~#007799 = $allports~~
- ~~#152340 = (none)~~
- ~~#152431 = $article-heading-color~~
- ~~#1b4a1b = $green-80~~
- ~~#a7a7a7 = …
=> PLANET-5842 Remove unused colors

src/base/_icons.scss, src/base/_typography.scss
See https://jira.greenpeace.org/browse/PLANET-5756
I've also removed the link hover color to align with the design system and https://jira.greenpeace.org/browse/PLANET-5843
- master-theme: https://github.com/greenpeace/planet4-master-theme/pull/1295
=> PLANET-5756 Remove jQuery from external_link.js and pdf_icon.js

src/base/_icons.scss
See https://jira.greenpeace.org/browse/PLANET-6004
You can see the fixed links & buttons on [this page](https://www-dev.greenpeace.org/test-leda/links-and-buttons-with-icons/) for example.
Note: the issue with the width of the secondary buttons will be solved as part of [PLANET-5980](https://jira.greenpeace.org/browse/PLANET-5980).
- [master-theme](https://github.com/greenpeace/planet4-master-theme/pull/1335)
- [blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/531)
=> PLANET-6004 Fix pdf link icon (hover) colors

src/base/_typography.scss, src/layout/_forms.scss, src/layout/_navbar.scss
See https://jira.greenpeace.org/browse/PLANET-5981
Changes made to comply with the [migration doc](https://getbootstrap.com/docs/5.0/migration/):
- Add margin-bottom to the `form-group` class
- Add `form-select` to select components instead of `form-control` (which now has `appearance: none;` hiding the select's arrow) + add small fix for rtl direction
Additional clean-up:
- Remove `screen-reader-text` class to use Bootstrap's `visually-hidden` instead
You can check the changes on [this test instance](https://www-dev.greenpeace.org/test-janus/), basically everything should look/behave the same as it does in the current sites 🙂 
- [gutenberg-blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/521)
- [master-theme](https://github.com/greenpeace/planet4-master-theme/pul …
=> PLANET-5981 Updates for Bootstrap 5

src/base/_icons.scss, src/base/_typography.scss, src/components/_buttons.scss
See [PLANET-5980](https://jira.greenpeace.org/browse/PLANET-5980)
- Header alignment choice (left/right/center) not reflected in the frontend
- Image alignment breaks text and creates gaps
- Button manually chosen text color not applied properly in the frontend
Should also solve [PLANET-5857](https://jira.greenpeace.org/browse/PLANET-5857)
- Weird breaks in paragraphs and lists with HTML tags (bold, anchor links, etc)
- [gutenberg-blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/519)
=> PLANET-5980 Fix inconsistencies between editor and frontend
