greenpeace/planet4-styleguide

- src/campaigns/_theme_oil.scss
- src/index.scss
Ref: https://jira.greenpeace.org/browse/PLANET-3722
> PLANET-3722 - Add Anton font for the Oil Campaign

- src/base/_fonts.scss
- src/base/_typography.scss
- src/components/_blockquote.scss
- src/components/_buttons.scss
- src/components/_tweet-block.scss
- src/layout/_breadcrumbs.scss
- src/layout/_cookies.scss
- src/layout/_footer.scss
- src/layout/_navbar.scss
- src/layout/_page-header.scss
- src/layout/_page-section.scss
Ref: https://jira.greenpeace.org/browse/PLANET-3701
Related master-theme PR: https://github.com/greenpeace/planet4-master-theme/pull/850
Related blocks PR: https://github.com/greenpeace/planet4-plugin-blocks/pull/612
> PLANET-3701: Include predefined set for font sizes in CSS Styleguide

- src/campaigns/_theme_oil.scss
- src/layout/_navbar.scss
This will always display the current logo.
Also added the first campaign logo, as part of the relevant theme.
> Add logo section

- src/base/_fonts.scss
- src/base/_typography.scss
- src/components/_blockquote.scss
- src/components/_buttons.scss
- src/components/_share-buttons.scss
- src/layout/_cookies.scss
- src/layout/_footer.scss
- src/layout/_forms.scss
- src/layout/_navbar.scss
- src/layout/_page-header.scss
- src/layout/_page-section.scss
- src/layout/_tables.scss
I had one more font-size variable, since we have a few places that we use this huge font size (4rem). For the rest I did an approximation choice and checked with Backstop to make sure they don't cause any significant change.
> Replace fixed font sizes with variables

- src/layout/_footer.scss
- Styled footer to align icons if there are less than the usual 5
> PLANET-4139 Alignment of social media icons in all footers

- src/layout/_footer.scss
- fixed social icon spacings in footer
> PLANET-4139-fix fix social icon spacing

- src/layout/_page-header.scss
Ref: https://jira.greenpeace.org/browse/PLANET-4101
> PLANET-4101 - Add a class to page-header for handling missing title

- src/base/_icons.scss
- src/layout/_cookies.scss
- src/layout/_navbar.scss
This change required by the Webpack migration.
Ref: https://jira.greenpeace.org/browse/PLANET-4054
> PLANET-4054: Gutenberg Compatibility: Separate Bootstrap, layout styles and block styles in master theme

- src/components/_buttons.scss
Ref: https://jira.greenpeace.org/browse/PLANET-4152
> PLANET-4152 Add Gutenberg button classes

- src/layout/_navbar.scss
Ref: https://jira.greenpeace.org/browse/PLANET-4206
⚠️ heads up! there is a master theme PR for this too: https://github.com/greenpeace/planet4-master-theme/pull/930
> PLANET-4206: Align navigation bar items

- src/layout/_cookies.scss
Discovered by Julia in the comments:
Ref: https://jira.greenpeace.org/browse/PLANET-3749
> PLANET-3749: Cookies bar iteration - background fix

- src/components/_buttons.scss
- Added file block download button to our secondary button styles
> PLANET-4154 FILE Block: adjust button style and functionality

- src/base/_icons.scss
- src/layout/_cookies.scss
- src/layout/_navbar.scss
Ref: https://jira.greenpeace.org/browse/PLANET-4428
See Gutenberg plugin PR: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/149
for some details.
Related master-theme PR: https://github.com/greenpeace/planet4-master-theme/pull/962
> PLANET-4428: Webpack: Source maps don't work	

- src/layout/_footer.scss
- src/layout/_navbar.scss
Ref: https://jira.greenpeace.org/browse/PLANET-4526
> PLANET-4526: GP Israel - Capital letters not rendered in frontend (Country Selector - Copyright)

- src/layout/_forms.scss
add css for toggle button.
Ref: https://jira.greenpeace.org/browse/PLANET-4595
> PLANET-4595 Archive - Implement command to include archived content in search results

- src/layout/_cookies.scss
Ref: https://jira.greenpeace.org/browse/PLANET-4486
Related Master Theme PR: https://github.com/greenpeace/planet4-master-theme/pull/997
> PLANET-4486: MENA: Cookies text and buttons are not aligned or resized properly (Tablet and Desktop) 

- src/components/_share-buttons.scss
https://jira.greenpeace.org/browse/PLANET-4766
> PLANET-4766 Fix vertical alignment of icons in share buttons

- src/layout/_navbar.scss
Ref: https://jira.greenpeace.org/browse/PLANET-4325
This depends on the master theme PR:
https://github.com/greenpeace/planet4-master-theme/pull/1035
> PLANET-4833: P4CG - Add language selector to minimal navigation

- src/base/_colors.scss
- src/components/_share-buttons.scss
Ref: https://jira.greenpeace.org/browse/PLANET-4906
Related master theme PR: https://github.com/greenpeace/planet4-master-theme/pull/1051
> PLANET-4906: Create UI for Whatsapp share button

- src/layout/_footer.scss
- src/layout/_navbar.scss
Note: Despite of the scope of the issue, I'll add any missing CSS variables in this PR.
Ref: https://jira.greenpeace.org/browse/PLANET-4820
Master theme PR: https://github.com/greenpeace/planet4-master-theme/pull/1048
Blocks PR: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/247
> PLANET-4820: P4CG - Footer color should not be applied when "Main website navigation" is selected

- src/components/_buttons.scss
- src/layout/_page-header.scss
- src/layout/_page-section.scss
This already passed UAT.
Ref: https://jira.greenpeace.org/browse/PLANET-4887
Blocks PR: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/252
Master Theme PR: https://github.com/greenpeace/planet4-master-theme/pull/1056
> PLANET-4887: Text that is #000000 should be #1A1A1A

- src/components/_buttons.scss
[Related PR](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/251)
> PLANET-4924 Fix new core buttons block style

- src/base/_colors.scss
- src/layout/_footer.scss
See https://jira.greenpeace.org/browse/PLANET-5001
> PLANET-5001 Footer link colors

- src/layout/_tables.scss
See https://jira.greenpeace.org/browse/PLANET-5037
> PLANET-5037 Remove table background colors in spreadsheets

- src/layout/_navbar.scss
[JIRA 5081](https://jira.greenpeace.org/browse/PLANET-5081)
Related [PR #1100](https://github.com/greenpeace/planet4-master-theme/pull/1100)
> PLANET-5081 Add 'Enhanced mobile Donate button' style

- src/layout/_navbar.scss
See https://jira.greenpeace.org/browse/PLANET-5088
Corresponding master-theme PR: https://github.com/greenpeace/planet4-master-theme/pull/1102
> PLANET-5088 Hide search icon when input is in focus and not empty

- src/base/_body.scss
- src/base/_colors.scss
- src/base/_typography.scss
- src/layout/_breadcrumbs.scss
See https://jira.greenpeace.org/browse/PLANET-5079 (UAT already passed)
Corresponding master-theme PR: https://github.com/greenpeace/planet4-master-theme/pull/1113
> PLANET-5079 Update inline links rollover color

- src/base/_typography.scss
- src/layout/_page-header.scss
- src/layout/_page-section.scss
See https://jira.greenpeace.org/browse/PLANET-5080 (including Will's latest comment, a lot of the information is there)
- Corresponding master-theme PR: https://github.com/greenpeace/planet4-master-theme/pull/1126
- Corresponding gutenberg-blocks PR: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/307
> PLANET-5080 Apply same typography across all P4 blocks

- src/components/_blockquote.scss
- src/layout/_blocks.scss
- src/layout/_page-header.scss
- src/layout/_tables.scss
See https://jira.greenpeace.org/browse/PLANET-5116 (UAT already passed)
- Corresponding master-theme PR: https://github.com/greenpeace/planet4-master-theme/pull/1109
- Corresponding plugin-gutenberg-blocks PR: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/299
> PLANET-5116 - Fix block vertical spacing

- src/base/_body.scss
- src/base/_colors.scss
- src/components/_blockquote.scss
- src/components/_buttons.scss
- src/layout/_page-header.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5082
Related PRs:
https://github.com/greenpeace/planet4-plugin-gutenberg-engagingnetworks/pull/53
https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/312
https://github.com/greenpeace/planet4-master-theme/pull/1128
> PLANET-5082: Accessibility change red based greys to blue based ones.

- src/base/_typography.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5263
> PLANET-5263: Decrease H1 size on mobile 

- src/layout/_footer.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5269
> PLANET-5269: Fix footer on mobile

- src/base/_body.scss
- src/base/_typography.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5362
> PLANET-5362 Remove duplicate declaration and add vars

- src/base/_icons.scss
> PLANET-5231 apply link styles to pdf icons

- src/layout/_forms.scss
- src/layout/_navbar.scss
See https://jira.greenpeace.org/browse/PLANET-5613
- [master-theme](https://github.com/greenpeace/planet4-master-theme/pull/1237)
- [gutenberg-blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/433)
> PLANET-5613 Add border-radius to all form fields

- src/components/_share-buttons.scss
See https://jira.greenpeace.org/browse/PLANET-5704
> PLANET-5704 Add rounded corners to share buttons

- src/layout/_footer.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5730
> PLANET-5730 Footer: Reverse last child icon margin for RTL

- src/base/_icons.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5708
> PLANET-5708: Fix colors for PDF icons inside secondary buttons

- src/base/_body.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5754
---
We [already have that](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/assets/src/styles/blocks/Submenu.scss#L120-L123), but moving it to the right place.
> PLANET-5754 Add smooth scrolling

- src/base/_fonts.scss
- src/layout/_forms.scss
- [PLANET-5705](https://jira.greenpeace.org/browse/PLANET-5705): update form input styles (border, fonts, colors)
- [PLANET-5512](https://jira.greenpeace.org/browse/PLANET-5512): add label/placeholder animation
- master-theme: https://github.com/greenpeace/planet4-master-theme/pull/1253
- gutenberg-blocks: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/454
> PLANET-5705 - Update form inputs UI

- src/layout/_cookies.scss
See https://jira.greenpeace.org/browse/PLANET-5755
- gutenberg-blocks: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/506
- master-theme: https://github.com/greenpeace/planet4-master-theme/pull/1306
> PLANET-5755 Remove jQuery from cookies

- src/base/_colors.scss
- src/base/_icons.scss
- src/base/_typography.scss
- src/components/_buttons.scss
- src/components/_skip-links.scss
- src/layout/_breadcrumbs.scss
- src/layout/_cookies.scss
- src/layout/_footer.scss
- src/layout/_navbar.scss
See https://jira.greenpeace.org/browse/PLANET-5843
**Black / Grey colors:**
- ~~#000000 = $black -> replace by #020202 = $grey-80~~
- ~~#030403 = $header-footer-bg -> replace by #020202 = $grey-80~~
- ~~#1a1a1a = none -> replace by #020202 = $grey-80~~
- ~~#052a30 = $dark-tiber -> replace by #020202 = $grey-80~~
- ~~#242424 = none -> replace by #23292d = $grey~~
- #a7a7a7 = $step-number -> unused, was removed with https://jira.greenpeace.org/browse/PLANET-5842
- #aaaaaa = none -> replace by #a3a5a7 = $grey-20 -> couldn't find it, seems unused
**Blue colors:**
- ~~#0a3351 = $med-blue -> replace by #074365 = $dark-blue~~
- ~~#094464 = $cookie-blue -> replace by #074365 = $dark-blue~~
- ~~#014c8c = $menu-blue ->replace by #020202 = $grey-80~~
- ~~#0058cc = $link-hover-color -> replace by …
> PLANET-5843 Replace some colors to align with the design system

- src/components/_share-buttons.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5906
See the [master theme PR](https://github.com/greenpeace/planet4-master-theme/pull/1305) for more information.
There's also a [blocks PR](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/505)
> PLANET-5906: Migrate to Bootstrap 5

- src/base/_typography.scss
- src/components/_share-buttons.scss
- src/layout/_forms.scss
- src/layout/_navbar.scss
Opening a pull request already for this branch into `master`, since there is already a pull request against it https://github.com/greenpeace/planet4-styleguide/pull/104
> Bootstrap 5 breaking changes
